### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by idkjs** [jihchi/app-template-reason-react#1]
Does this work with `create-snowpack-app`? Or do we just clone this?

If cloning maybe put a template tag on it?

Doesn't seem to work unless you take out `clean-world` from `snowpack.config.js` or change the order to `clean-world` first:

```js
  "scripts": {
    "run:re,rei": "bsb -clean-world && bsb -make-world",
    "run:re,rei::watch": "$1 -w"
  },
```

Thanks for doing this!

**Comment by jihchi** [comment]
> Does this work with create-snowpack-app? Or do we just clone this?

Yes, this work with create-snowpack-app and it is recommended approach:

```
npx create-snowpack-app new-dir --template app-template-reason-react [--use-yarn]
```

> Doesn't seem to work unless you take out clean-world from snowpack.config.js or change the order to clean-world first: ...

I've merged #2 and published `v1.3.2`.

Thanks for the PR.
